### ISSUE TITLE
When image is rotated the lens got inverted axis

### ISSUE THREAD

**Issue by GabrielBragaGit** [henczi/ng-magnizoom#14]
It would be interesting if the lens control didn't have its axis rotated like the image when using 'transform: rotate(Xdeg)'. It's difficult to control.

**Comment by henczi** [comment]
Yes, you are right, it can be pretty annoying and difficult to control...

Keep in mind, that - in most cases - it is not a good practice to use a magnifying effect on a rotated image, however in some cases, it is necessary or it can be very helpful, so I implemented a basic CSS transform support in version `1.3.0`.

Check out the new version!

**Comment by sterichards** [comment]
Hello, @henczi 

I have this same issue and using [imageStyle] like in your StackBlitz demo, I cannot create a rotation of 90 / 180 / 270 degrees without the axis being incorrect

Implementing 90 / 180 / 270 directly as an option into your project would be amazing because it is a very common rotation value

But still, I can see your 45 demo with a working axis but I cannot see how to update your example to make the axis work correctly for 90 / 180 / 270

Please can you help

**Comment by henczi** [comment]
Hi @sterichards,

I've added a couple more rotation examples to the Stackblitz demo, I hope that helps you.

Keep in mind that in your project you will have to update the dependency to `1.3.0` to have this feature.

**Comment by sterichards** [comment]
> Hi @sterichards,
> 
> I've added a couple more rotation examples to the Stackblitz demo, I hope that helps you.
> 
> Keep in mind that in your project you will have to update the dependency to `1.3.0` to have this feature.

Thank you. I think the new examples will help me a lot!
